/* This file was generated by github.com/ronanyeah/elm-port-gen */

interface ElmApp {
  ports: Ports;
}

interface Ports {
  airdrop: PortOut<null>;
  zkLogin: PortOut<null>;
  getBalance: PortOut<null>;
  log: PortOut<string>;
  copy: PortOut<string>;
  transfer: PortOut<{
    target: string;
    amount: string;
  }>;
  logout: PortOut<null>;
  walletCb: PortIn<Wallet>;
  sigCb: PortIn<string>;
  balanceCb: PortIn<string>;
}

interface PortOut<T> {
  subscribe: (_: (_: T) => void) => void;
}

interface PortIn<T> {
  send: (_: T) => void;
}

interface Wallet {
  address: string;
  ephPublic: string;
  googleSub: string;
}

export { ElmApp, Wallet };
